name: Maven

on:
  workflow_call:
    inputs:
      projectName:
        default: ${{ github.workflow }}
        required: false
        type: string
      containerRegistry:
        default: ''
        required: false
        type: string
      gitTag:
        required: true
        type: string

jobs:

  buildAndTest:
    name: Maven Build & Test
    runs-on: [self-hosted]
    steps:
      - name: Maven Build
        shell: bash
        run: |
          echo "Run Build Maven here!"

  BuildContainerImage:
    name: Build & Push Container Image
    needs: buildAndTest
    runs-on: [self-hosted]
    steps:
      # - name: Checkout Project Repo
      #   uses: actions/checkout@v3
      # - name: Check out global-actions repository
      #   uses: actions/checkout@v3
      #   with:
      #     repository: KTijssen/global-actions
      #     ref: beta
      #     # token: ${{ secrets.PAT_TOKEN }}
      #     path: "global-actions"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_RO_TOKEN }}

      - name: Build Container Image (Main/Master)
        uses: kevintijssen/docker-build-push@v1
        if: github.ref_name == 'main' || github.ref_name == 'master'
        with:
          command: build
          name: kevintijssen/${{ inputs.projectName }}
          registry: ${{ inputs.containerRegistry }}
          tags: ${{ inputs.gitTag }}, latest

      - name: Push Container Image (Main/Master)
        uses: kevintijssen/docker-build-push@v1
        if: github.ref_name == 'main' || github.ref_name == 'master'
        with:
          command: push
          name: kevintijssen/${{ inputs.projectName }}
          registry: ${{ inputs.containerRegistry }}
          tags: ${{ inputs.gitTag }}, latest

      - name: Build Container Image (PR)
        uses: kevintijssen/docker-build-push@v1
        if: github.ref_name != 'main' || github.ref_name != 'master'
        with:
          command: build
          name: kevintijssen/${{ inputs.projectName }}
          registry: ${{ inputs.containerRegistry }}
          tags: ${{ inputs.gitTag }}

      - name: Push Container Image (PR)
        uses: kevintijssen/docker-build-push@v1
        if: github.ref_name != 'main' || github.ref_name != 'master'
        with:
          command: push
          name: kevintijssen/${{ inputs.projectName }}
          registry: ${{ inputs.containerRegistry }}
          tags: ${{ inputs.gitTag }}